language: node_js
services:
  - mongodb
node_js:
  - '0.11'
before_install:
  - gem install sass
  - npm install -g gulp
  - npm install -g bower
  - npm install -g npm
  - npm install
  - gulp install-client
  - gulp dev-build
install:
  - gulp start-serv &
  - gulp pagespeed
